Add findUseHardcodedFilter(N)
wiremod/wire pull request #2084
Opened 2020-08-31 23:16 UTC by TomyLobo

findUseHardcodedFilter(1) - (default behaviour) Use the hardcoded entity type filter from A Land Before Git History
findUseHardcodedFilter(0) - Don't.

2020-09-01 01:48 UTC, thegrb93 commented
Can't think of any case where removing the filter would break anything. The function name is currently really bad either way though. Need something more user friendly.

2020-09-01 06:10 UTC, syranide commented
(per your request) I don't believe I wrote this file, at the very least I have no memory of it whatsoever. I believe the find-extension was written by someone else. My two guesses would be that certain interactions with e.g. `info_` entities could crash or break something. I have a vague memory of specifically excluding E2 chips from certain interactions to avoid "hijacking", but that was probably more in-relation to the "wireless data transfer" and not being able to send data to other players E2s and so on.

2020-09-01 07:00 UTC, syranide commented
Found this: https://web.archive.org/web/20090204202900/http://wiki.garrysmod.com/wiki/?title=Wire_Expression2#Entity_Discovery 😄

"Developed by: Gwahir"

2020-09-02 18:30 UTC, TomyLobo commented
Testing on gm_sunsetgulch:
```C
@name findUseHardcodedFilter-test
@inputs 
@outputs 
@persist 
@trigger 

findUseHardcodedFilter(0)
findByClass("prop_dynamic")
R = findToArray()
print(R:count())
printTable(R)
```
Result:
https://steamcommunity.com/sharedfiles/filedetails/?id=2217526713

2020-09-02 19:29 UTC, Divran commented
might need a better name

2020-09-03 00:45 UTC, thegrb93 requested changes
I'd just remove the default filter

2020-09-03 22:52 UTC, TomyLobo commented
@thegrb93 That'd break some existing E2s

2020-09-03 23:52 UTC, thegrb93 commented
do et :).

Alternatively maybe name it like 'findIncludeBlockedClasses(1)' or something

2020-09-04 18:50 UTC, TomyLobo commented
@thegrb93 The `findInclude*` functions operate on the whitelists. If you want to confuse people, that's a great way to do it :)
The `findAllow*` functions operate on the blacklists, so findAllowBlockedClasses(1) would be better.
What say you, @Divran?

2020-09-04 18:53 UTC, TomyLobo commented
@thegrb93 hmm, one issue with that: The hardcoded filter also filters out the chip itself and the new name does not reflect that.

2020-09-04 20:09 UTC, Divran commented
@TomyLobo simply make this change still filter out the chip itself

2020-09-04 20:41 UTC, TomyLobo commented
Changed name, put the chip filter back, added an E2Helper description and tested the whole shebang again.

2020-09-05 07:55 UTC, thegrb93 approved these changes

2020-09-07 00:22 UTC, merged