Add a system for automatically cleaning up tables with player keys on disconnect
wiremod/wire pull request #2110
Opened 2020-12-06 19:20 UTC by TomyLobo

2020-12-06 19:46 UTC, Divran commented
Haven't tested ingame but it looks good.

2020-12-06 20:37 UTC, TomyLobo commented
Meh, when was the last time that check succeeded?
I'm giving up, it's good enough. I even fixed some bugs along the way

2020-12-06 21:31 UTC, thegrb93 commented
Did you have to put the cleanup in the same pr >v<

2020-12-07 22:36 UTC, thegrb93 commented
The player table commits look fine. I didn't review all the cleanup changes yet, mind making a different branch and cherry picking them to that one and then removing them from this one?

2020-12-10 04:51 UTC, thegrb93 requested changes

2020-12-10 04:51 UTC, thegrb93 commented on lua/entities/gmod_wire_egp/lib/egplib/queuesystem.lua
> +		end
Going to swap this and remove the not

2020-12-10 04:51 UTC, thegrb93 commented on lua/wire/wire_paths.lua
> +			end
Flip this too

2020-12-10 04:52 UTC, thegrb93 commented
Everything else looks fine. Finally reviewed it all.

2020-12-10 07:05 UTC, thegrb93 approved these changes
Didn't see any errors. I don't have many EGP to test with though.

2020-12-10 07:10 UTC, merged

2020-12-12 00:51 UTC, TomyLobo commented
Yeah i thought we had a requirement to fix all the luacheck errors that pop up.
That's why I put this in the same PR.
Thanks for testing it btw.