Allow E2 to write (and read) files other than .txt
wiremod/wire pull request #2152
Opened 2021-03-21 21:54 UTC by Vurv78

Allows E2 to write and read txt, dat json, jpg, xml, csv, and any other file extensions that are allowed by garrysmod. Useful if you for some unholy reason make a PNG writing library in E2 (I definitely didn't do that)

Adds a SHARED E2Lib function ``isValidFilePath`` that simply returns if it has an extension, and if that extension is on the whitelist.

2021-03-21 23:02 UTC, Divran commented
> Useful if you for some unholy reason make a PNG writing library in E2 (I definitely didn't do that)
🤔

2021-03-21 23:04 UTC, thegrb93 commented
Can you change the name to IsValidFileWritePath? IsValidFilePath is too ambiguous

2021-03-22 00:22 UTC, Vurv78 commented
Changed to isValidFileWritePath

2021-03-22 00:49 UTC, thegrb93 approved these changes

2021-03-22 00:51 UTC, thegrb93 commented
There's one thing that's been worrying me about this capability.

What if there's a break/exploit in the loaders of these files that users can now write and load?

2021-03-22 00:52 UTC, thegrb93 commented
the vmt,vtf,mp3,ogg,wav formats are the most worrying as a malformed file could possible crash if the engine isn't hardened enough to them.

2021-03-22 03:28 UTC, Anticept commented
I would strongly advise an admin configurable whitelist defaulted to only safe, non-executable text extensions. Everything else should require an admin to purposely enable additional functionality. I echo the same concerns as thegrb93, but this should be a reasonable balance.

2021-03-23 01:55 UTC, thegrb93 commented
I think the gmod devs wouldn't whitelist those files if there were any exploits with them, the most worrisome being arbitrary code execution. I think it is fine.

2021-03-23 18:31 UTC, TomyLobo commented
The gmod devs don't have our threat model.
We cannot rely on their decisions.
See also: HTTP
Just rename your .png files .txt if you think you can load those.


... next?

2021-03-23 18:32 UTC, TomyLobo requested changes
The gmod devs don't have our threat model.
We cannot rely on their decisions.
See also: HTTP
Just rename your .png files .txt if you think you can load those.
We could merge the refactoring that moves all the file type checks into one place. That part is nice.


... next?

2021-03-23 19:10 UTC, Fasteroid commented
I agree with thegrb93, why would Facepunch whitelist a file extension if it were potentially dangerous?  They already learned their lesson in the past with the *cough* virus in 2008 or so.  And the bigger issue there was the lack of directory restriction rather than file type restriction.

> the vmt,vtf,mp3,ogg,wav formats are the most worrying as a malformed file could possibly crash if the engine isn't hardened enough to them.
Unless someone finds a way to break out of E2's sandbox, this SHOULD BE a non-issue.  I do not recall E2 having any functions that can actually use this data on the engine level natively.  If some extension enables this for some reason, the blame falls on the extension.  Most of these files are meaningless in e2's serverside context anyway.

> Just rename your .png files .txt if you think you can load those.
If you can just rename anything to .txt anyway I don't see the point in restricting file types to begin with.  If the argument is that the data itself is somehow problematic to upload (say a particular byte sequence is bad), changing the file extension doesn't do anything—it's still the same data and will cause the same engine-level issues uploading/downloading.  Not sure what the point in restricting this is.

+1 on Vurv's idea.  Not sure where the issue is.

2021-03-23 19:12 UTC, Fasteroid commented
> **thegrb93**
> the vmt,vtf,mp3,ogg,wav formats are the most worrying as a malformed file could possibly crash if the engine isn't hardened enough to them.

Unless someone finds a way to break out of E2's sandbox, this SHOULD BE a non-issue.  I do not recall E2 having any functions that can actually use this data on the engine level natively.  If some extension enables this for some reason, the blame falls on the extension.  Most of these files are meaningless in e2's serverside context anyway.

2021-03-23 19:13 UTC, Fasteroid commented
> **TomyLobo**
> Just rename your .png files .txt if you think you can load those.

If you can just rename anything to .txt anyway I don't see the point in restricting file types to begin with.  If the argument is that the data itself is somehow problematic to upload (say a particular byte sequence is bad), changing the file extension doesn't do anything—it's still the same data and will cause the same engine-level issues uploading/downloading.  Come to think of it I'm not sure what the point in restricting this was in the first place

2021-03-23 21:19 UTC, TomyLobo commented
E2's sandbox is irrelevant to this. You can assume it's unbroken and still open up a whole new class of potential exploits to a whole new class of attackers.
Also, I'm not sure if you misinterpreted my suggestion to rename as "make E2 able to rename files", but just to be clear, I am not advocating that, nor would I ever, because that is a similar recipe for disaster, perhaps even worse. I am telling them to work around by renaming their .png files to .txt _manually_.
And no, I'm not talking about the upload/download itself, either, obviously.

2021-03-23 21:54 UTC, thegrb93 commented
It that's true then servers could already be sending such exploited resources to clients and infecting their computers. The gmod devs and valve were very careful in preventing and fixing such exploits as they were found. I don't think allowing this in E2 poses any threat.

2021-03-24 22:32 UTC, merged