Kill large forces to prevent crashes
wiremod/wire pull request #2202
Opened 2021-07-22 23:14 UTC by Python1320

A better kill constant should be experimented with, but it is at least less than half of maximum float (2^128). Clamping might or might not make more sense.

2021-07-26 04:34 UTC, thegrb93 requested changes

2021-07-26 04:34 UTC, thegrb93 commented on lua/entities/gmod_wire_thruster.lua
> +	self.ForceAngular		= self.ThrustOffset:GetNormalized() * -1
Looks like this can actually be removed since SetForce will set it anyway

2021-07-26 04:34 UTC, thegrb93 commented on lua/entities/gmod_wire_thruster.lua
> -	self.ForceAngle		= self.ThrustOffset:GetNormalized() * -1
These are set already in Initialize() right? Should just remove these, also the lines above.

2021-07-26 07:14 UTC, Divran commented
This function <https://github.com/wiremod/wire/blob/master/lua/wire/wireshared.lua#L1024> is already a thing. Maybe it'd be good to use it here as well?

2021-07-26 07:22 UTC, thegrb93 commented
Yeah I suppose that's better. Could you also replace that function with
```lua
function WireLib.clampForce( v )
	return Vector(
		v[1] == v[1] and math.Clamp( v[1], min_force, max_force ) or 0,
		v[2] == v[2] and math.Clamp( v[2], min_force, max_force ) or 0,
		v[3] == v[3] and math.Clamp( v[3], min_force, max_force ) or 0
	)
end
```

2021-07-29 17:46 UTC, thegrb93 requested changes

2021-07-29 17:46 UTC, thegrb93 commented on lua/entities/gmod_wire_thruster.lua
> +		self.effectforce = self.ThrustOffset:Length() * (self.force * self.mul * -50)
My mistake here. Should be positive 50 instead of negative and also don't need parentheses.

2021-07-29 17:46 UTC, thegrb93 commented on lua/entities/gmod_wire_vectorthruster.lua
> -		self:CalcForce(phys)
Should revert the self.calcforce changes and instead set self.calcforce to false in this if

2021-08-08 00:43 UTC, thegrb93 commented on lua/entities/gmod_wire_vectorthruster.lua
> -		self:CalcForce(phys)
The force is actually global so nvm

2021-08-08 03:29 UTC, merged