Merge my wire addons into wire
wiremod/wire pull request #2231
Opened 2021-09-26 17:51 UTC by stepa2

This PR includes two my addons:

- [Improved RT Cameras](https://github.com/stepa2/improved-rt-cameras) [(Workshop)](https://steamcommunity.com/sharedfiles/filedetails/?id=2566118330)
Adds working wire-compatible render target cameras
- [Expression 2 Entity Manipulation](https://github.com/stepa2/e2_entitymanipulation) [(Workshop)](https://steamcommunity.com/sharedfiles/filedetails/?id=2510195508)
Allows spawning engine entities, changing keyvalues and datadesc, firing inputs and hooking outputs. **Highly unsafe**, but powerful.

After (if) this PR will be merged, I plan to archive original repositories and remove workshop pages.

####  Required fixes
- Add entmanipulation spawn whitelist configuration GUI (Defaults are [here](https://steamcommunity.com/workshop/filedetails/discussion/2510195508/3111404628288556424/))

2021-09-26 18:02 UTC, Vurv78 requested changes
Small reviews from just glancing at this.
I think adding ``e:fire`` and ``e:setkeyvalues`` in any form, even with a whitelist, is an awful idea. You even acknowledge how badly this could be abused.  A lot of servers just randomly turn on every E2 core in wiremod as well.

Maybe this could make it into wire extras since it's more lenient, but right now I don't support this (dunno about the RT cameras)

2021-09-26 18:02 UTC, Vurv78 commented on lua/entities/gmod_wire_expression2/core/custom/entmanipulation.lua
> +local E2_TABLE_DEFAULT = {n={},ntypes={},s={},stypes={},size=0}
You should be using ``E2Lib.newE2Table``, not this and constantly cloning

2021-09-26 18:22 UTC, stepa2 commented on lua/entities/gmod_wire_expression2/core/custom/entmanipulation.lua
> +e2function table entity:entKVsGet()
It I checked entity keyvalues, inputs, input values and datadesc values for validness, I could create three safety profiles:
1. Fully safe: players only can spawn whitelisted entities, fire whitelisted inputs etc.
2. Safe for non-admins: usual players can only use whitelisted functionality, admins can do everything
3. Unsafe mode: everyone can do everything

2021-09-26 18:28 UTC, stepa2 commented
It I checked entity keyvalues, inputs, input values and datadesc values for validness, I could create three safety profiles:

    Fully safe: players only can spawn whitelisted entities, fire whitelisted inputs etc.
    Safe for non-admins: usual players can only use whitelisted functionality, admins can do everything
    Unsafe mode: everyone can do everything

2021-09-26 20:18 UTC, stepa2 commented
I will not include EntManipulation (maybe later...)

2021-09-26 23:18 UTC, Divran commented
Yeah the e2 entity extension could probably never be added. To wire extras, and disabled by default, maybe, but not in main wiremod.

Also I would recommend merging the two tools to spawn an RT camera and screen, into one tool where left click does one thing and right click the other.

2021-09-27 07:28 UTC, stepa2 commented
In future I would like to add support to rendering RT camera contents to EGP, and RT camera will not always be used with RT monitor. So I do not want to merge tools and treat RT camera and RT monitor as a complementary pair.

2021-09-28 12:41 UTC, stepa2 commented
Code is ready-to-merge

2021-09-28 12:43 UTC, Divran commented
> In future I would like to add support to rendering RT camera contents to EGP, and RT camera will not always be used with RT monitor. So I do not want to merge tools and treat RT camera and RT monitor as a complementary pair.

Eh, I disagree that merging the tools implies you can't also use them for other things

2021-09-29 14:06 UTC, stepa2 commented
If I will merge tools, settings will take too many space.

![изображение](https://user-images.githubusercontent.com/24942438/135284571-d2427603-4eaa-4b89-8bef-7b00154f2bc2.png)
![изображение](https://user-images.githubusercontent.com/24942438/135284651-d34fd6e6-f28f-4c6d-b30b-b0bee2b6333f.png)

2021-09-29 16:25 UTC, thegrb93 commented
Code looks fine to me

2021-09-29 17:31 UTC, merged

2021-09-29 20:26 UTC, Divran commented
There's a function in the code called `SetMaterialParams` which doesn't seem to be defined anywhere. It's also not documented on the gmod wiki. What does this function do?

2022-01-29 03:41 UTC, RadioactvePixels commented
RT Cameras cause a massive FPS drop... 2 FPS with 3 cameras/screens.