Add exponential ops limit for parentTo
wiremod/wire pull request #2254
Opened 2021-12-01 06:03 UTC by Vurv78

Like I mentioned in #2252 I dunno if this is our place but I have a fix here.  
My server could only handle a chain of ~50 props parented before dying so the limit here is around 40.

Should fix #2252

2021-12-01 06:09 UTC, thegrb93 commented
I don't think this actually fixes the crash. Also you can defeat the op limit by parenting its head prop to a new head rather than parenting new props to the chain.

2021-12-01 06:10 UTC, thegrb93 commented
What's actually causing the crash?

2021-12-01 06:14 UTC, Vurv78 commented
Unfreezing the top prop instantly kills the server for me, and it seems this needs to be even less lenient :/

2021-12-01 06:24 UTC, thegrb93 commented
This needs to compute the length of the parent chain the prop is being parented to, compute the max chain length of props parented to the prop being parented, and add those two chain lengths together to get the total length; then determine whether they can be parented based on that.

2021-12-01 06:26 UTC, thegrb93 commented
Also, I wouldn't use ops to limit it because some places set ops really high

2021-12-01 08:32 UTC, thegrb93 commented
I tried reproducing a crash with this sf code. No crash

```lua
--@server

local e
for i=1, 120 do
    local ne = prop.create(chip():getPos() + Vector(0,0,40*i), Angle(), "models/Combine_Helicopter/helicopter_bomb01.mdl")
    if e then
        ne:setParent(e)
    end
    e = ne
end
```

2021-12-04 06:56 UTC, Vurv78 commented
Yeah the issue seems to be the weird orientation they were spawned in actually... so this is more of a matter of providing an automated way to create some prop crash blob. Was able to reproduce with your code modified to use the local position in the E2 code

```lua
--@server

local function fn(name)
    return function(x)
        return math[name]( math.rad(x) )
    end
end
local sin, cos = fn("sin"), fn("cos")

local e
for i = 1, 256 do
    local RelativePos = Vector( sin(i * 20) * 10, cos(i * 20) * 10, i)
    local ne = prop.create(chip():localToWorld(RelativePos), Angle(), "models/props_junk/PopCan01a.mdl", 0)
    if e then
        ne:setParent(e)
    end
    e = ne
end
```

2021-12-04 07:39 UTC, thegrb93 commented
I'll take another look at it

2021-12-04 10:16 UTC, thegrb93 commented
I think it makes sense to limit the chain depth

2021-12-04 10:32 UTC, thegrb93 commented
```lua

local function chainLength(parent, child)
	local index = parent
	local parentLength = 0
	while index:IsValid() do
		parentLength = parentLength + 1
		index = index:GetParent()
	end

	local function getChildLength(curchild, count)
		local max = 0
		for k, v in pairs(curchild:GetChildren()) do
			max = math.max(max, getChildLength(v, count + 1))
		end
		return max
	end
	local childLength = getChildLength(child, 1)

	return parentLength + childLength
end
```

2021-12-05 13:13 UTC, thegrb93 commented
Adding `ent:PhysicsDestroy()` before parenting also seem to fix the crash

2021-12-05 23:22 UTC, Vurv78 commented
ent:PhysicsDestroy() doesn't seem to stop the crash for me

2021-12-06 13:30 UTC, thegrb93 commented
Ah well, I added the code I posted to starfall. if you want to add it to this branch then I can merge.

2021-12-07 02:32 UTC, Vurv78 commented
Done, didn't make it hard error (only errors on ``@strict``) since I don't know if that would incur the wrath of a lot of massive laggy contraptions

2021-12-07 02:42 UTC, thegrb93 requested changes
The recursive parent check is pointless since gmod devs added code to prevent that since it used to crash the engine.

2022-01-04 22:10 UTC, merged