Fix bootleg detonator damaging method
wiremod/wire pull request #2371
Opened 2022-07-21 16:16 UTC by Andrew-Eathan

not sure what to write here, i tested the code and it has the behavior i expect

2022-07-21 17:36 UTC, thegrb93 commented
Need to make sure it still breaks breakable props that typically don't take damage, like the cannon ball prop.

2022-07-22 21:05 UTC, thegrb93 commented
Yeah, the cannon ball prop doesn't explode 'models/props_phx/cannonball.mdl'. Try changing the damage type to something else.

2022-07-22 21:05 UTC, thegrb93 requested changes
Yeah, the cannon ball prop doesn't explode 'models/props_phx/cannonball.mdl'. Try changing the damage type to something else.

2022-07-24 11:02 UTC, Andrew-Eathan commented
DMG_GENERIC does the job

2022-07-25 20:48 UTC, thegrb93 commented
I'm going to test it on a couple more props

2022-07-28 14:05 UTC, Andrew-Eathan commented
e

2022-08-15 14:48 UTC, merged