Added e:setWeaponColor and e:setPlayerColor
wiremod/wire pull request #2378
Opened 2022-07-30 19:39 UTC by Smigg-y

Already tested this and it seems to work fine

https://user-images.githubusercontent.com/70798673/181971797-3c8e0d44-20c9-4c1f-8bec-03f65d0f4ea8.mp4

2022-07-30 19:47 UTC, Vurv78 requested changes

2022-07-30 19:47 UTC, Vurv78 commented on lua/entities/gmod_wire_expression2/core/color.lua
> +e2function vector entity:setWeaponColor(vector c)
These need to return void

2022-07-30 19:47 UTC, Vurv78 commented on lua/entities/gmod_wire_expression2/core/color.lua
> +    if not this:IsPlayer() then return self:throw("You cannot set the weapon color of non-players!", nil) end
Spaces -> Tabs

2022-07-30 19:49 UTC, Smigg-y commented on lua/entities/gmod_wire_expression2/core/color.lua
> +e2function vector entity:setWeaponColor(vector c)
wilco

2022-07-31 16:20 UTC, Vurv78 approved these changes

2022-08-12 07:28 UTC, merged