Update gmod_wire_forcer.lua
wiremod/wire pull request #2395
Opened 2022-08-31 18:56 UTC by Aws0mee

GravGunPunt usually returns true for most entities, but GravGunPickupAllowed is usually more restrictive and I think it makes more sense for this case. Should fix #1934

2022-08-31 19:25 UTC, thegrb93 commented
Should be a convar to pick between 3 options: no check, gravgun punt, and gravgun pickup. with it defaulting to gravgun punt. It should also still be able to force players with any option.

2022-08-31 19:25 UTC, thegrb93 requested changes
More options

2022-09-01 05:22 UTC, Aws0mee commented
> Should be a convar to pick between 3 options: no check, gravgun punt, and gravgun pickup. with it defaulting to gravgun punt. It should also still be able to force players with any option.

They should have 3 options now. By default it will be the same as it was before, but if they want they can configure it to how they like it. You mentioned that you want it to be able to force players no matter which option they have, but how it is not they will be able to decide in the hook if they want players to be able to be forced or not. I think that is the best option as some servers like darkrp and such probably don't want people being flung across the map with forcers.

Let me know if you want any changes.

2022-09-01 19:47 UTC, thegrb93 commented
could you make the options separate if else's instead of a monolithic expression.

```
if option==0 then
elseif option==1 then
elseif option==2 then
end
```

2022-09-02 00:24 UTC, Aws0mee commented
> could you make the options separate if else's instead of a monolithic expression. i.e.
> 
> ```
> if option==0 then
> elseif option==1 then
> elseif option==2 then
> end
> ```

I think it looks uglier after the changes, but let me know what you think.

2022-09-02 02:04 UTC, thegrb93 commented
Can you check if it works now. Can merge if so.

2022-09-02 02:38 UTC, Aws0mee commented
Just tested, wire_forcer_permissions 0 causes everything to be pushed. 1, allows players and doors to be pushed by default, and 2 allows players to be pushed but does not allow doors to be pushed by default.

2022-09-02 04:55 UTC, merged

2022-09-02 04:55 UTC, thegrb93 commented
Went ahead and merged it but removed the 'Should fix https://github.com/wiremod/wire/issues/1934' because my comment there is the actual fix.