Remove c operators
wiremod/wire pull request #2416
Opened 2022-09-09 19:21 UTC by Aws0mee

Removed every C operator. I did not find and replace all, I manually checked every operator I changed so hopefully I didn't make any mistakes. I would appreciate if other could let me know if I made and incorrect changes or missed any.

2022-09-12 10:20 UTC, dvdvideo1234 commented
https://www.youtube.com/watch?v=755BDwzxv5c

2022-09-27 18:40 UTC, Aws0mee commented
Just double checked all the changes and tested the code. Seems to work fine on my server. I'll convert this into an actual PR in a few days unless someone notices any issues.

2022-10-01 19:58 UTC, mmiller1250 commented
This works on my server

2022-10-10 06:40 UTC, Vurv78 approved these changes
Works fine in my basic tests

2022-10-10 18:14 UTC, thegrb93 requested changes

2022-10-10 18:14 UTC, thegrb93 commented on lua/entities/gmod_wire_expression2/core/table.lua
> +			if (!rv1.s[rv2] or rv1.stypes[rv2] ~= id) then return fixDefault(v[2]) end
Missed some `!`

2022-10-10 18:16 UTC, thegrb93 commented on lua/entities/gmod_wire_holoemitter.lua
> +			self:SetNWBool(name,not (value == 0 and true) or false)
Just replace this garbage ternary with `value ~= 0`

2022-10-10 18:16 UTC, thegrb93 commented on lua/entities/gmod_wire_holoemitter.lua
> +			if (self.bools[name]) then value = not (value == 0 and true) or false end
Just replace this garbage ternary with `value ~= 0`

2022-10-10 18:17 UTC, thegrb93 commented on lua/entities/gmod_wire_holoemitter.lua
> +		self.Data.LineBeam = not (value == 0 and true) or false
Fix these too

2022-10-10 18:36 UTC, thegrb93 commented on lua/entities/info_wiremapinterface/init.lua
> +	if (IsValid(Entity._WireMapInterfaceEnt) and (Entity._WireMapInterfaceEnt ~= self)) then return false end -- Only one interface per entitynot
This replace is wrong

2022-10-17 21:37 UTC, thegrb93 approved these changes

2022-10-18 22:33 UTC, merged

2022-10-19 07:08 UTC, dvdvideo1234 commented
![](https://i.kym-cdn.com/photos/images/newsfeed/000/714/215/281.jpg)