Add anti-aliasing option to editor
wiremod/wire pull request #2455
Opened 2022-10-17 17:54 UTC by marchcain

Adds anti-aliasing to the E2 code editor

![gmod_vaTXkY8w80](https://user-images.githubusercontent.com/13711445/196247795-9a0189b3-1f71-4bad-b8ac-96236fa0c222.gif)

2022-10-17 20:45 UTC, Divran commented
also fixes #2446

2022-10-17 20:46 UTC, Divran approved these changes
didnt test ingame but looks good to me

2022-10-20 00:52 UTC, Vurv78 requested changes

2022-10-20 00:52 UTC, Vurv78 commented on lua/wire/client/text_editor/wire_expression2_editor.lua
> +	local antialias = self.FontAntialiasingConvar:GetInt() > 0 and true or false
Change this to `self.FontAntialiasingConvar:GetBool()`

2022-10-20 00:54 UTC, Vurv78 commented
Maybe this could be turned on by default as well? What's the opinion on this?

2022-10-29 01:20 UTC, Vurv78 approved these changes

2022-10-29 01:20 UTC, merged

2022-10-29 02:26 UTC, Divran commented
> Maybe this could be turned on by default as well? What's the opinion on this?

@Vurv78 I haven't looked ingame to compare but it's possible the default e2 font looks better with antialiasing disabled. Not all fonts are designed for it, or work with it in all sizes. If you want to make it default on, check if it makes it look like shit first.