Fix freezer causing error when unfreezing without owner
wiremod/wire pull request #2479
Opened 2022-11-07 05:50 UTC by Aws0mee

Fixes #2478

2022-11-07 22:09 UTC, Vurv78 commented
Does the `CanPlayerUnfreeze` hook also need this check?

2022-11-08 05:33 UTC, Aws0mee commented
> Does the `CanPlayerUnfreeze` hook also need this check?

No, it does not appear to cause any errors from my testing. Refer to #2478

2022-11-08 22:19 UTC, thegrb93 commented
Can you just put an `if not IsValid(self:GetPlayer()) then return end` at the top of the triggerinput? Pretty sure the other hooks in there will want it.

2022-11-08 22:20 UTC, thegrb93 requested changes
Can you just put an if not IsValid(self:GetPlayer()) then return end at the top of the triggerinput? Pretty sure the other hooks in there will want it.

2022-11-09 04:22 UTC, thegrb93 commented
It's not going to work anyway if it's spitting lua errors

2022-11-09 04:22 UTC, thegrb93 commented
The only way it will ever work if owner disconnects is if gmod ever got a decent prop protection which isn't happening.

2022-11-09 11:22 UTC, Aws0mee commented
> The only way it will ever work if owner disconnects is if gmod ever got a decent prop protection that works by steamid checks when the owner is disconnected, but I don't see that ever happening.

Fair enough, I changed it.

2022-11-09 14:57 UTC, merged