Additional Turret Options
wiremod/wire pull request #2508
Opened 2022-12-04 23:35 UTC by Hazeofdream

had this on my drive for awhile and figure I'd through this out if any dev/contributor is interested in this.

tl;dr adds blast radius and blast damage to turrets so people don't have to cheese wire explosives/prop explosives for their bullet based contraptions

Adds Convars for these values since 1) hardlocking/clamping like the damage was done is gross and 2) it's a pretty uh, *colorful function*

Not immediately suggesting to pull this as I haven't figured out how to maintain old turrets as this would modify it's inputs, and even duplicating it would mean having to make seperate turrets just based on whether servers had this. I GUESS that would be the best option if their is no alternative

obligatory not a good coder probably has some unncessary/dogshit code in it but lmao i tried

2022-12-07 21:38 UTC, Vurv78 requested changes
Haven't tested in game but these are my reviews.

2022-12-07 21:38 UTC, Vurv78 commented on lua/entities/gmod_wire_turret.lua
> +-- Legacy Support
Lua doesn't have any sort of overloads. This just replaces the previous function `Setup` with a different one that takes the old parameters

2022-12-07 21:38 UTC, Vurv78 commented on lua/entities/gmod_wire_turret.lua
> +	self.blastdamage = math.Clamp( blastdamage, 0, GetConVar("wire_turret_blastdamage_max") )
`GetConVar` returns the actual `ConVar` object. You want either `GetConVar(...):GetInt()` or `GetConVarInt(...)`.

Ideally you'd keep the convar outside of the function, and then just call GetInt on that whenever SetBlastDamage is called

2022-12-07 21:38 UTC, Vurv78 commented on lua/entities/gmod_wire_turret.lua
> +	self.blastradius = math.Clamp( blastradius, 0, GetConVar("wire_turret_blastradius_max") )
Same as above

2022-12-07 21:38 UTC, Vurv78 commented on lua/entities/gmod_wire_turret.lua
> +-- Legacy Support
Once again not how this works, pretty sure this would just overwrite the other one.

2022-12-07 21:38 UTC, Vurv78 commented
I'm not really sold on the idea right now. I think maybe this could be its own component, like `gmod_wire_cannon` or something to really make it obvious that it blows stuff up.

Also so that server owners can properly restrict it, since I think people would want to restrict a fully automatic exploding bullet weapon a lot more than just a typical bullet turret.

2022-12-07 21:39 UTC, Vurv78 commented on lua/entities/gmod_wire_turret.lua
> +-- Legacy Support
If you want to fix this stuff and have proper legacy support you need to put the blast damage / radius inputs after the trace ones

2022-12-08 00:39 UTC, thegrb93 commented
Seems mingey

2022-12-08 04:50 UTC, Hazeofdream commented
> Seems mingey
_laughs in wire explosive_

2022-12-08 05:44 UTC, thegrb93 commented
Well, a lot of servers restrict explosives. Now you've added something else for them to have to restrict

2022-12-08 05:47 UTC, thegrb93 commented
I like that wire_cannon idea. Especially if it is like a modifiable acf cannon.

2022-12-09 00:15 UTC, Hazeofdream commented
sounds like a seperate wire turret with extra steps

2022-12-10 23:12 UTC, Hazeofdream commented
I'll try the cannon idea but leave this here for now, It probably wont be the most advanced thing either tho so don't expect acf levels of customization.

2022-12-14 18:52 UTC, closed without merging