EGP Enhancements and Fixes
wiremod/wire pull request #2571
Opened 2023-05-17 08:17 UTC by Denneisk

## Easy
- [X] #2546 
- [X] #2553 
- [X] Feature mentioned in #2553 
## Possibly not easy
- [ ] #2190
- [ ]  #2282
- [ ] #2473 
  - ?
## Not not easy but kind of annoying
- [ ] Fix formatting to conform to style
- [ ] #1476
  - Probably skip this one

2023-05-17 15:24 UTC, wrefgtzweve commented
If i remember correctly, EGP data is broadcasted to all players regardless if they're using it or not. It would be cool if it only sends EGP data once the chip is being used.

2023-05-17 15:38 UTC, Denneisk commented
> If i remember correctly, EGP data is broadcasted to all players regardless if they're using it or not. It would be cool if it only sends EGP data to players using the chip.

EGP HUD data you mean? I believe that's already how it's done but I'll look into it.

2023-05-18 11:50 UTC, Divran commented
> If i remember correctly, EGP data is broadcasted to all players regardless if they're using it or not. It would be cool if it only sends EGP data to players using the chip.

I don't remember how that worked but it sounds very likely given that when egp was made we only had usmg and if someone new walked up and started using the hud it would have taken ages to sync everything back then. But with the newer transfer method it should be a lot faster

2023-05-18 21:56 UTC, KemGus commented
Finally somebody is fixing the issues in EGP!
I really hope to see further improvements in the future. Do you plan on making EGP great again?

2023-05-18 22:22 UTC, thegrb93 requested changes

2023-05-18 22:22 UTC, thegrb93 commented on lua/entities/gmod_wire_egp/lib/egplib/objectcontrol.lua
> +		if obj and obj.ChangeOrder then
This is just covering up a bug caused by something else. There should not be a nil partway in the RenderTable.

2023-05-18 22:22 UTC, thegrb93 commented on lua/entities/gmod_wire_egp/lib/egplib/transmitreceive.lua
Don't mix format/style changes with code changes. It makes reviews more painful than they need to be.

2023-05-18 23:05 UTC, Denneisk commented on lua/entities/gmod_wire_egp/lib/egplib/transmitreceive.lua
Yeah, sorry about that.

2023-05-19 16:40 UTC, Denneisk commented
Here's your proper solution lol

2023-05-30 14:27 UTC, thegrb93 commented on lua/entities/gmod_wire_egp/init.lua
> +function ENT:UpdateTransmitState() return TRANSMIT_PVS end
This shouldn't be changed. The entity should always exist for clients in order to stay in sync.

2023-05-30 14:32 UTC, thegrb93 commented on lua/entities/gmod_wire_expression2/core/egpfunctions.lua
> +	if not EGP.Objects.Names[objectName] then self:throw("EGP object name '" .. objectName .. "' does not exist!") end
Need to make sure you're doing `return self:throw(`

2023-05-30 21:07 UTC, Denneisk commented
A quick look at some EGP creations doesn't reveal anything besides the expected; E2s that use DrawTopLeft will have to be modified in lieu of the fix.

2023-06-01 04:26 UTC, Denneisk commented
Putting back in drafts to address some recent considerations.

2023-06-17 02:08 UTC, closed without merging

2023-06-17 04:20 UTC, thegrb93 commented
EGP never failed to destroy the willpower of anyone who touches it