Render-Target Camera and Screen fixes
wiremod/wire pull request #2576
Opened 2023-05-21 12:36 UTC by stepa2

- Fixes broken RT Screen material variants dropdown
- Fixes RT Camera darkening when halos are rendered
- Fixed some cases when last frame from disabled RT Camera are shown

Halo fix detours Garry's mod hook for drawing halos. Proper PR to garrysmod repo needed.

2023-05-22 13:47 UTC, thegrb93 commented on lua/wire/client/cl_wirelib.lua
> +assert(old_renderhalos ~= nil, "Garry's mod internals updated, halos are now rendered in some other way")
Use an if statement and ErrorNoHalt and put your hook.Add inside the if.

2023-05-22 13:48 UTC, thegrb93 commented on lua/wire/client/cl_wirelib.lua
> +assert(old_renderhalos ~= nil, "Garry's mod internals updated, halos are now rendered in some other way")
Everything else looks fine. Can merge with that fixed

2023-05-22 15:02 UTC, thegrb93 approved these changes

2023-05-22 15:11 UTC, thegrb93 requested changes

2023-05-22 15:27 UTC, stepa2 commented on lua/wire/client/cl_wirelib.lua
> +local old_renderhalos = old_renderhalos or hook.GetTable().PostDrawEffects.RenderHalos
https://wiki.facepunch.com/gmod/Auto_Refresh#breakingcode

2023-05-22 15:35 UTC, thegrb93 commented on lua/wire/client/cl_wirelib.lua
> +local old_renderhalos = old_renderhalos or hook.GetTable().PostDrawEffects.RenderHalos
In that case, I think you need to use a global, not a local.

2023-05-22 15:55 UTC, stepa2 commented on lua/wire/client/cl_wirelib.lua
> +local old_renderhalos = old_renderhalos or hook.GetTable().PostDrawEffects.RenderHalos
Why would others need access to old hook implementation?

2023-05-22 17:16 UTC, thegrb93 commented on lua/wire/client/cl_wirelib.lua
> +local old_renderhalos = old_renderhalos or hook.GetTable().PostDrawEffects.RenderHalos
I don't think autorefresh preserves local vars. You'd need a global to ensure that the value is preserved. If you think it does preserve local vars, can you test that out and make sure of it? That really doesn't seem right to me.

2023-05-22 20:19 UTC, stepa2 commented on lua/wire/client/cl_wirelib.lua
> +local old_renderhalos = old_renderhalos or hook.GetTable().PostDrawEffects.RenderHalos
Well, you are right.

2023-05-22 21:38 UTC, thegrb93 approved these changes

2023-05-23 18:04 UTC, stepa2 commented
Are you waiting for me to finish #2578 before merging this PR and #2577?

2023-05-23 18:24 UTC, thegrb93 commented
No, just giving other reviewers a chance to look

2023-05-24 00:53 UTC, merged

2023-05-24 23:51 UTC, Aws0mee commented
@stepa2 does this PR fix this?
![image](https://github.com/wiremod/wire/assets/51889746/d7df4200-200a-427d-b1f6-54bd35d2de87)