E2 sound extensions
wiremod/wire pull request #2578
Opened 2023-05-21 13:57 UTC by stepa2

- Exports some SoundCore functions
- Adds SoundCore functions from modified xtrasound core (https://steamcommunity.com/sharedfiles/filedetails/?id=2221932128)
- Adds EmitSound core - a simplier way to play sounds

2023-05-22 14:35 UTC, thegrb93 commented
I don't think we need a new extension for the emitsound functions. Thoughts, @Vurv78 ?

2023-05-22 22:17 UTC, Vurv78 commented
I agree, don't see any reason for them to be separate, especially if having them separate is will need you to export fields in `E2Lib`.

2023-05-22 22:20 UTC, Vurv78 commented
As for the rest of the unused exported fields, why? Maybe I'd understand IsAllowed in case you want to configure that as an admin, but why not just make a hook then? And I *really* don't like the idea of other addons depending on internal code like that (especially with #2555)

2023-05-24 09:52 UTC, stepa2 commented
Originally soundcore stuff was exported because extra sound functions (`soundDsp`, etc.) were in separate core.

2023-05-24 23:47 UTC, Vurv78 requested changes

2023-05-24 23:47 UTC, Vurv78 commented on lua/wire/client/e2descriptions.lua
> +E2Helper.Descriptions["emitSound"] = "Plays sound on entity. Note that one file can only be played once in a time."
These are invalid, need `emitSound(e:snnn)`, `emitSound(e:snn)`, `emitSound(e:sn)`, `emitSound(e:s)`, `emitSoundStop(e:s)`

2023-05-30 14:08 UTC, merged