Implement ConVars
wiremod/wire pull request #2702
Opened 2023-07-30 03:24 UTC by Hazeofdream

Fixes #2592 and makes certain wire turret options convars instead of having bias against multiplayer sessions.

2023-07-30 04:06 UTC, Vurv78 requested changes
No stealth buffs :p

2023-07-30 04:06 UTC, Vurv78 commented on lua/entities/gmod_wire_turret.lua
> +local NumEnabled = CreateConVar("wire_turret_numbullets_enabled", 1, {FCVAR_NOTIFY, FCVAR_ARCHIVE, FCVAR_REPLICATED}, "Enable or Disable the numbullets function of wire turrets")
Should not be enabled by default, should be `game.SinglePlayer() and 1 or 0`.

2023-07-30 04:06 UTC, Vurv78 commented on lua/entities/gmod_wire_turret.lua
> +local MinTurretDelay = CreateConVar("wire_turret_delay_minimum", 0.01, {FCVAR_NOTIFY, FCVAR_ARCHIVE, FCVAR_REPLICATED}, "Set the minimum allowed value for wire turrets")
Should not be 0.01 by default, should be `game.SinglePlayer() and 0.01 or 0.05`

2023-07-30 04:06 UTC, Vurv78 commented on lua/wire/stools/turret.lua
> +	CPanel:NumSlider("#Delay", "wire_turret_delay", GetConVar("wire_turret_delay_minimum"):GetBool(), 1.0, 2)
GetFloat not GetBool

2023-07-31 20:34 UTC, Hazeofdream commented
haha that works too

2023-08-02 21:01 UTC, thegrb93 commented
I'm fine with the buffs, they can be turned down by servers who don't want it.

The one thing I'm not sure of is the values in 'NumSlider'. is it min,max,default? Some of the defaults look weird if so.

2023-08-02 21:35 UTC, Vurv78 commented
Only thing was numbullets which I saw disabling would allow someone to set a turret to spawn infinite bullets, but now it's force clamped so, although turrets being able to shoot 5x faster is a pretty big buff

2023-08-03 02:01 UTC, Hazeofdream commented
ultimately, wire can only be regulated properly by the server owners, wiremod's attempts to but in on their behalf is either unwelcome or won't work

2023-08-03 02:07 UTC, Hazeofdream commented
> The one thing I'm not sure of is the values in 'NumSlider'. is it min,max,default? Some of the defaults look weird if so.

apparently the last value is an optional decibel value, so some values like 0 on damage means no decimal damage. They still look wack though

2023-08-03 02:51 UTC, thegrb93 commented
Ah ok

2023-08-03 02:51 UTC, merged