Optimize EGP HUD Drawing
wiremod/wire pull request #2747
Opened 2023-09-12 09:08 UTC by Denneisk

Fixes this code vomit.

2023-09-12 09:17 UTC, Denneisk commented
Might be able to do this better by just having `hudPaint` not even draw and instead just steal from the pre-existing RenderTable.

2023-09-12 16:18 UTC, thegrb93 commented on lua/entities/gmod_wire_egp_hud/cl_init.lua
> +if EGP then -- If the table has been loaded
This if check isn't needed nor is the initialize hook. Mind deleting those too?

2023-09-12 20:22 UTC, thegrb93 commented on lua/entities/gmod_wire_egp/cl_init.lua
> +	self.RenderTable = table.Copy(EGP.HomeScreen)
Need `self.NeedsUpdate = true` here too right?

2023-09-12 20:32 UTC, thegrb93 commented
Looks good, just make sure to test it a bunch. Looks potentially breaking

2023-09-14 17:57 UTC, Denneisk commented
Got so confused looking at this thinking this was the object rewrite.

2023-09-20 03:10 UTC, thegrb93 requested changes

2023-09-20 03:10 UTC, thegrb93 commented on lua/entities/gmod_wire_egp_hud/init.lua
> +	self:SetNWBool("Resolution", false)
Could this be an entity NetworkVar instead of NW? NW tends to be less reliable.

2023-09-20 05:34 UTC, merged