Fix issues involving math.tau
wiremod/wire pull request #3054
Opened 2024-04-29 15:12 UTC by Denneisk

Many users have been complaining about the number extension suddenly not working. This is because some servers don't have `math.tau` defined on them for whatever reason. This PR presents a twofold solution:

1. It sets a fallback for `math.tau` when it is undefined.
2. It ensures any future invalid constants will not cause extensions to fail loading.

- Add fallback for `math.tau`
- Change error in `E2Lib.registerConstant` to use `WireLib.Notify` instead so invalid constants don't break the extension.
- Added some context to the errors in `E2Lib.registerConstant` (This functionality should probably be moved to its own function)
- Added timeout for `WireLib.Notify` "nudges" on the client

Updated error form (note E2 executes extension files twice):
![New errors](https://github.com/wiremod/wire/assets/20892685/7322f368-3e1d-4e79-b5ed-61d7e1943629)

2024-04-29 18:28 UTC, Denneisk commented
Messed up something with the git history whatever

2024-04-30 20:03 UTC, thegrb93 requested changes

2024-04-30 20:03 UTC, thegrb93 commented on lua/wire/client/cl_wirelib.lua
> +			notify_antispam = time
```suggestion
		local time = CurTime()
		if severity > 1 and notify_antispam < time then
			notify_antispam = time + 1
```

2024-05-01 02:38 UTC, thegrb93 approved these changes

2024-05-01 02:38 UTC, merged

2024-05-01 07:09 UTC, Grocel commented
> This is because some servers don't have `math.tau` defined on them for whatever reason.

That's because GMod updates are optional and servers are outdated sometimes. The math.tau constant was added in last main update. Rubat's tip toeing around net compatibility makes it possible that server could be outdated by 2+ years and still be able to connect to. Good look accounting for those servers in addon code on the long run.