Update new expression2 file comment
wiremod/wire pull request #3083
Opened 2024-06-10 16:11 UTC by deltamolfar

Makes it a little more modern.
Can be used to tell players that don't sit on Discord/don't follow GitHub updates what's new.
Informs regulars players about events/lambdas.

2024-06-10 16:16 UTC, wrefgtzweve commented
I feel like updates shouldn't be in there as it'll likely rarely be updated.

2024-06-10 16:17 UTC, deltamolfar commented
If so, it can be renamed to latest features, to inform about latest big stuff

2024-06-10 16:18 UTC, wrefgtzweve commented
My point still stands then, a string in a file somewhere isn't a good way to display new features and will simply age poorly.

2024-06-10 16:35 UTC, Periapsises reviewed
Nice overall, but some grammar mistakes here and there.

2024-06-10 16:35 UTC, Periapsises commented on lua/wire/client/text_editor/wire_expression2_editor.lua
> +    - What is events, and their benefits
```suggestion
    - What are events and their benefits
```

2024-06-10 16:35 UTC, Periapsises commented on lua/wire/client/text_editor/wire_expression2_editor.lua
> +    - Other directives(like @model)
```suggestion
    - Other directives (like @model)
```

2024-06-10 16:35 UTC, Periapsises commented on lua/wire/client/text_editor/wire_expression2_editor.lua
> +    - What is lambda functions, and their benefits
```suggestion
    - What are lambda functions and their benefits
```

2024-06-10 16:36 UTC, Periapsises commented
> My point still stands then, a string in a file somewhere isn't a good way to display new features and will simply age poorly.

I don't think a lot of people will remember to include their changes in there.
If there was a way to automate it, that would be great.

2024-06-10 16:41 UTC, deltamolfar commented
Thanks @Periapsises, I commited them

2024-06-10 17:02 UTC, Denneisk commented
I think the changelog is going to be more trouble than it's worth. I'd like an in-editor changelog feature as well but I haven't thought on how to best approach such a thing.

The phrase "and their benefits" seems a little tacky in my opinion. :P

2024-06-10 17:04 UTC, deltamolfar commented
Changelog - well tbh no idea, you lads can keep it or remove it, I don't really mind.

But "And their benefits" is for those that doesn't want to learn new things, and switch to better ways of doing things.

2024-06-10 17:33 UTC, deltamolfar commented
Regarding news, I think separate file with new and old news can easily be added, which later on could be used to show news, with an inbox icon (similar to credits icon) with a read/not read support. Code wise it would just be a panel with static text from the said file

2024-06-10 18:50 UTC, thegrb93 requested changes
A changelog should be read from something else that regularly gets updated.
Too much info about the docs.

2024-06-10 22:18 UTC, deltamolfar commented
Well, it can be done like that. To be honest I don't particulary care about the description format as much, as about it being informative about concepts that aren't easily discoverable by E2Helper (lambdas, events, and why @strict) mainly

2024-06-11 21:48 UTC, Denneisk approved these changes

2024-06-11 22:11 UTC, thegrb93 approved these changes

2024-06-13 22:33 UTC, merged