E2 sentSpawn function.
wiremod/wire pull request #3085
Opened 2024-06-13 00:12 UTC by deltamolfar

- Finally a way for E2 to spawn sents.
- For QoL, limited to wire/native gmod sents + entity tab entities, if `wire_expression2_propcore_whitelist <= 0`)
- Thirdparty addons support (ability to add/remove ents to be able to be spawned within whitelist + a hook with same logic as `Expression2_CanEffect`
- Entity registration is straightforward, and the sentSpawn does all the E2 to Lua castings itself (No need to put every check in _preFactory'ies).

I've tested **all** registered by defaults sents. (The only sent I couldn't get to work is `gmod_wire_dynamic_button`.)

While most of registration code/logic is from starfall `prop_sent.lua`, I've found and fixed ~10 sents + added ~6 that weren't originally there.

The only "problem" there currently is, is that undo for some reason doesn't return `E2 sent (classname)`, but `e2_spawned_sent`.

2024-06-13 00:35 UTC, wrefgtzweve commented
This should be a separate core or some kind of workshop addon core.

2024-06-13 00:59 UTC, deltamolfar commented
Why? With whitelist convar on (which is on by default) - you can spawn only wire entities + a few basic gmod sends (lamp, button, etc). You can't spawn a weapon/vehicle/etc with that.

2024-06-13 12:47 UTC, GDZCHNIK commented
Wow, it`s cool thing

Uploading Download (13).mp4…

2024-06-13 12:48 UTC, GDZCHNIK commented
This E2 sentSpawn function so 
cool, i1`m cumming!1!1!

2024-06-13 12:50 UTC, Zenius07 commented
Cool, this is very useful

2024-06-13 12:52 UTC, GDZCHNIK commented
This function very helpful, because the original E2 has limitations and so I can't write advanced codes

2024-06-13 12:52 UTC, Swanchick commented
Hell yeah, these things should have been added before!!!

2024-06-13 15:10 UTC, deltamolfar commented
Can you elaborate how an ability to spawn, say, a button, a security risk? And about abuse - same goes to propspawning explosive barrels? There is way more and way stronger ways to abuse then spawning wire elements. If you really want, I can easily add additional convar, to disable sentSpawn, but I can't see, how spawning a wire element can be security, or abuse risk, except for maybe spawning a wire explosive, but you already can pre-spawn and reuse it, or spawn an explsoive barrel?

As I said, I did not deliberately call anyone, but sent it to my old dev team to review the code, and PR in general. Or do you hold responsibility for actions of everyone else you know?

Also, I may be wrong, but why and other people that use sf often use ability of spawning sents as one of major advantages, and tell how E2 is bad because of absence of that feature, but now you against it being added?

2024-06-13 20:01 UTC, wrefgtzweve commented
I don't see a big issue with default/wire ents as long as they're specifically filtered like they are in starfall. The security risk was aimed at the `wire_expression2_propcore_whitelist` which at first value seemed like it allows players to spawn *any* entity
`CreateConVar("wire_expression2_propcore_sents_whitelist", "1", FCVAR_ARCHIVE) -- 1: Players can spawn sents only that are added to the default sent list, 0: Players can spawn any sent (no way to make players not spawn errors then though!)`
which would've been a major issue. However it seems like it only allows you to spawn props from the spawn menu.
Having a way to toggle sentSpawn on/off with a convar would be great though.

2024-06-13 20:05 UTC, deltamolfar commented
Yeah, comment is a bit misleading, will fix that.
Alright, I will add a convar to disable sentSpawn altogether.
Also I will comment default gmod ents from whitelist, as I think they don't fit well there, and may lead to some form of light/effect abuse (as wire and native light/emitters are not sharing same limit).

2024-06-13 20:07 UTC, wrefgtzweve commented
As long as the entities follow the prop limit (which i think this does) it should be fine.

2024-06-13 22:06 UTC, deltamolfar commented
Added the convar to outright disable sentSpawn, and done some cleaning. Found out that while gmod_emitter and gmod_camera spawn as expected, they just don't want to work. Sadly I will have free time in few days-week. Until them I've left them commented

2024-06-14 13:42 UTC, wrefgtzweve commented
For `wire_expression2_propcore_sents_whitelist` you should use `:GetBool()` instead of `:GetInt()` would make more sense

2024-06-14 15:33 UTC, Denneisk requested changes
Minor things. It seems okay so far.

2024-06-14 15:33 UTC, Denneisk commented on lua/entities/gmod_wire_expression2/core/custom/prop.lua
> +			return false
Can simplify this to `return e2Value > 0`

2024-06-14 15:33 UTC, Denneisk commented on lua/entities/gmod_wire_expression2/core/custom/prop.lua
> +				for i, value in ipairs(e2Value["n"]) do
Should use `pairs` since `n` is not expected to be sequential in E2 tables.

2024-06-14 15:33 UTC, Denneisk commented on lua/entities/gmod_wire_expression2/core/custom/prop.lua
> +	return 0
```suggestion
	return WithinPropcoreLimits() and 1 or 0
```

2024-06-14 20:14 UTC, closed without merging

2024-06-14 20:21 UTC, deltamolfar commented
Fuck. Accident lmao