Fix various linter issues
wiremod/wire pull request #3108
Opened 2024-07-20 22:32 UTC by wrefgtzweve

Fixes a load of linter errors, doesn't fix all of them but i didn't want to make the PR too big.

2024-07-22 17:51 UTC, thegrb93 requested changes

2024-07-22 17:51 UTC, thegrb93 commented on lua/entities/gmod_wire_cameracontroller.lua
> -	local curdistance = 0
This removed local is still referenced. There seems to be some bugs here still. Don't trust the linter blindly.

2024-07-22 17:51 UTC, thegrb93 commented on lua/entities/gmod_wire_cameracontroller.lua
> -	local ParentLocal = false
Same goes for this one

2024-07-22 17:51 UTC, thegrb93 commented on lua/entities/gmod_wire_sensor.lua
> +		--local BeaconPos = self.Inputs["Target"].Src:GetBeaconPos(self)
Remove comment

2024-07-22 17:51 UTC, thegrb93 commented on lua/entities/gmod_wire_lamp.lua
> -	local matBeam		= Material( "effects/lamp_beam" )
This local is referenced in some dead commented code. Delete the commented code.

2024-07-22 17:51 UTC, thegrb93 commented on lua/wire/client/customspawnmenu.lua
> -	local x,y = self.List:GetPos()
Put this local back since removing it is destroying code consistency.

2024-07-22 17:51 UTC, thegrb93 commented on lua/wire/client/customspawnmenu.lua
> -local expand_all = CreateConVar( "wire_tool_menu_expand_all", 0, {FCVAR_ARCHIVE} )
Put this local back since removing it is destroying code consistency.

2024-07-22 17:51 UTC, thegrb93 commented on lua/wire/client/sound_browser.lua
> -	local soundemitter = false
This variable is still referenced

2024-07-22 17:51 UTC, thegrb93 commented on lua/wire/client/sound_browser.lua
> -		local nduration, strduration = FormatLength(nduration, nsize)
Put this local back since removing it is destroying code consistency.

2024-07-22 17:51 UTC, thegrb93 commented on lua/wire/client/sound_browser.lua
> -	local oldw, oldh = SoundBrowserPanel:GetSize()
Put this local back since removing it is destroying code consistency.

2024-07-22 17:51 UTC, thegrb93 commented on lua/entities/gmod_wire_light.lua
> -		local w,h = surface.GetTextSize( color_text )
Put this local back since removing it is destroying code consistency.

2024-07-22 17:51 UTC, thegrb93 commented on lua/entities/gmod_wire_indicator.lua
> -		local w,h = surface.GetTextSize(color_text)
Put this local back since removing it is destroying code consistency.

2024-07-22 17:52 UTC, thegrb93 commented
You better double check everything or I'm straight up closing it. I hate reviewing these kinds of PRs.

2024-07-23 16:22 UTC, wrefgtzweve commented
Yeah i can understand that, as for the unused variables it should probably be turned off in the linter then because they show up with wiremods settings.
I imagine it'd be better if i did singular changes, eg a PR that only changes `//` to `--`.

2024-07-23 22:19 UTC, thegrb93 commented
That would be far easier to review, yeah.

2024-07-23 22:31 UTC, wrefgtzweve commented
👍 I'll do a follow up PR for those sometime then, currently im a bit busy but i'll eventually get around it

2024-07-23 22:31 UTC, closed without merging