Merge Wire Extras' holoAnim core with the vanilla hologram core
wiremod/wire pull request #3113
Opened 2024-08-03 17:04 UTC by unknao

People have been talking about porting Wire Extras e2 cores on and off on the Wiremod discord for quite a while since Wire Extras might be undesireable for some server owners that don't want the abuseability of some of the other things added by it.

I fixed up the broken pose parameters and added some new functions that should make working with hologram animations easier.

2024-08-05 15:47 UTC, thegrb93 requested changes

2024-08-05 15:47 UTC, thegrb93 commented on lua/entities/gmod_wire_expression2/core/hologram.lua
> +			end
Should add some logic for animations to the hologram ENT:Think instead of doing this hackery

2024-08-06 14:24 UTC, unknao commented
It would be nice to have the ability to stop the entity from thinking too much when an animation is over, though i don't know any way to check if its over and not screw over looping animations.

2024-08-06 15:28 UTC, thegrb93 approved these changes

2024-08-08 16:26 UTC, merged