e:propNoDupe(n)
wiremod/wire pull request #3146
Opened 2024-10-13 21:55 UTC by deltamolfar

Makes a silly function that lets you mark props as nodupe, to prevent from duping over. Useful for making pre-spawned prop projectiles non-dupeable

2024-10-14 02:02 UTC, thegrb93 approved these changes

2024-10-14 08:47 UTC, deltamolfar commented
Good point. Will make it remember what has been set to no dupe by e2/owner bit later

2024-10-15 01:32 UTC, thegrb93 requested changes

2024-10-15 01:32 UTC, thegrb93 commented on lua/entities/gmod_wire_expression2/core/custom/prop.lua
> +	return (this.DoNotDuplicate==nil and not duplicator.IsAllowed(this:GetClass()) or this.DoNotDuplicate) and 0 or 1
```suggestion
	return (this.DoNotDuplicate == true or not duplicator.IsAllowed(this:GetClass())) and 0 or 1
```

2024-10-15 01:32 UTC, thegrb93 commented on lua/entities/gmod_wire_expression2/core/custom/prop.lua
> +local entMarkedNoDupeByPlayer = {}
Avoid using a table because it will leak memory. Maybe just add a E2_MarkedNoDupe var onto the entity itself.

2024-10-15 01:32 UTC, thegrb93 commented on lua/entities/gmod_wire_expression2/core/custom/prop.lua
> +	return entMarkedNoDupeByPlayer[cacheKey]!=true and (this.DoNotDuplicate==nil and not duplicator.IsAllowed(this:GetClass()) or this.DoNotDuplicate) and 0 or 1
cacheKey isn't defined here

2024-10-18 21:59 UTC, thegrb93 commented on lua/entities/gmod_wire_expression2/core/custom/prop.lua
> +	return ent.DoNotDuplicate != true -- If false or nil -> can mark as dupeable.
!= should be ~=

2024-10-18 22:01 UTC, thegrb93 commented on lua/entities/gmod_wire_expression2/core/custom/prop.lua
> +		if not canMarkDupeable(this, self.player) then return self:throw("Can't mark this entity as undupeable!", nil) end
Can move this check up to the top of the function and remove some of the other checks.

2024-10-18 22:02 UTC, thegrb93 commented on lua/entities/gmod_wire_expression2/core/custom/prop.lua
> +		this.DoNotDuplicate = nil
DoNotDuplicate should be true here and the other one should be nil

2024-10-18 22:03 UTC, thegrb93 commented on lua/entities/gmod_wire_expression2/core/custom/prop.lua
> +		this.DoNotDuplicate = nil
Something is reversed

2024-10-21 19:49 UTC, thegrb93 approved these changes

2024-10-27 03:29 UTC, merged