Increase precision of dot bounds check in EGP:DrawPath
wiremod/wire pull request #3184
Opened 2024-11-19 17:34 UTC by Denneisk

Fixes a bug with EGP CircleOutlines where the dot product could be >0.999 and <=1, causing the function to skip calculating every segment but the last.

As far as I can tell, having these so imprecise isn't actually necessary.

2024-11-19 23:07 UTC, thegrb93 requested changes
Can you change the comparators to >= and <=? Also move the local scaling calculation?

```lua
if dot >= 1 then
    ...
elseif dot <= -1 then
    ...
else
    local scaling = size*math.tan(math.acos(dot)/2)
    if dir.x*-lastdir.y + dir.y*lastdir.x > 0 then
        ...
    else
        ...
    end
end
```

2024-11-20 00:03 UTC, Denneisk commented
The function works fine at +/-1 but I'll oblige in case there's some weird precision issue.

2024-11-20 00:04 UTC, thegrb93 requested changes

2024-11-20 00:04 UTC, thegrb93 commented on lua/entities/gmod_wire_egp/lib/egplib/usefulfunctions.lua
> +					end
One too many 'end'?

2024-11-20 00:05 UTC, thegrb93 commented
> The function works fine at +/-1 but I'll oblige in case there's some weird precision issue.

It's supposed to take the simpler branch though as an optimization.

2024-11-20 00:19 UTC, Denneisk commented on lua/entities/gmod_wire_egp/lib/egplib/usefulfunctions.lua
> +					end
Yeah, must have gotten confused.

2024-11-20 00:20 UTC, thegrb93 approved these changes

2024-11-20 00:28 UTC, merged