Micro-optimizations for base_wire_entity
wiremod/wire pull request #3192
Opened 2024-11-30 21:25 UTC by Astralcircle

Basically just saves __index calls/caches colors

2024-11-30 23:39 UTC, Denneisk approved these changes

2024-12-01 23:14 UTC, thegrb93 requested changes

2024-12-01 23:14 UTC, thegrb93 commented on lua/entities/base_wire_entity.lua
> +
Revert this

2024-12-01 23:14 UTC, thegrb93 commented on lua/entities/base_wire_entity.lua
> +		if not name or name == "" then return ent:GetTable().PrintName else return name end
Revert this

2024-12-01 23:14 UTC, thegrb93 commented on lua/entities/base_wire_entity.lua
> +		if cur_ent ~= looked_at and IsValid(looked_at) and looked_at:GetTable().IsWire then
Revert this

2024-12-01 23:14 UTC, thegrb93 commented on lua/entities/base_wire_entity.lua
> +		if IsValid(cur_ent) and cur_ent:GetTable().IsWire and cur_ent:BeingLookedAtByLocalPlayer() then
Revert this

2024-12-01 23:14 UTC, thegrb93 commented on lua/entities/base_wire_entity.lua
>  	end
Need to investigate if this is even needed code anymore

2024-12-01 23:14 UTC, thegrb93 commented on lua/entities/base_wire_entity.lua
> +		if table.IsEmpty(halos) then return end
```suggestion
		if halos[1]==nil then return end
```

2024-12-01 23:14 UTC, thegrb93 commented on lua/entities/base_wire_entity.lua
> +		if name == "" then name = self:GetTable().PrintName end
Revert this

2024-12-01 23:14 UTC, thegrb93 commented on lua/entities/base_wire_entity.lua
> +	return tab and tab.OverlayData or nil
Revert this

2024-12-01 23:41 UTC, thegrb93 commented
Crap code for a pinch of performance. Entity __index does GetTable itself so its not that beneficial in places where you're only avoiding one __index call

2024-12-02 01:05 UTC, Denneisk commented
I was also questioning if `GetTable` in this usage was efficient but I assumed the best. With that said, some of these index calls are ran every tick (conditionally), and I think there's merit in having these changes there.

2024-12-02 06:30 UTC, thegrb93 approved these changes

2024-12-03 00:45 UTC, merged