tickRate function
wiremod/wire pull request #3218
Opened 2024-12-13 21:29 UTC by Astralcircle

A simple function that returns the current tickrate of the server. Can be useful to easily see server lags.

2024-12-13 21:48 UTC, Denneisk approved these changes
Sure, why not.

2024-12-13 22:44 UTC, wrefgtzweve commented
could be cool to also add https://gmodwiki.com/physenv.GetLastSimulationTime while you're at it

2024-12-13 23:53 UTC, thegrb93 requested changes

2024-12-13 23:53 UTC, thegrb93 commented on lua/entities/gmod_wire_expression2/core/serverinfo.lua
> +	return 1 / engine.AbsoluteFrameTime()
The function name is too similar to tickInterval. Should be realInterval and return engine.AbsoluteFrameTime() instead of the inverse.

2024-12-14 08:43 UTC, thegrb93 approved these changes

2024-12-14 08:43 UTC, merged