Fix lambda timers timerSetDelay not accounting for repetitions.
wiremod/wire pull request #3226
Opened 2024-12-24 08:12 UTC by unknao

Lambda timers used to make all timers infinitely repeat upon using timerSetDelay, now it accounts for timers with limited repetitions.

2024-12-24 15:09 UTC, Denneisk approved these changes

2024-12-24 15:15 UTC, Denneisk requested changes
Actually, sorry, I just double-checked, and you could just pass `nil` for the repetitions argument instead of needing to find them and reassign them.
https://wiki.facepunch.com/gmod/timer.Adjust

2024-12-25 07:46 UTC, unknao commented
Oh, that would've saved like half an hour of time if i had known that

2024-12-25 15:43 UTC, Denneisk approved these changes

2024-12-27 04:17 UTC, merged